global using Microsoft.EntityFrameworkCore;
global using BankingSystem.Domain.Entities;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using static BankingSystem.Infrastructure.EntityConfiguration.EntityConfigurationConstants;
global using BankingSystem.Application.Abstractions.Repository;
global using BankingSystem.Application.Abstractions.Services;
global using BankingSystem.Application.DTOs.AuthenticationDTOs;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using BankingSystem.Domain.Enums;
global using BankingSystem.Application.DTOs.TransactionDTOs;
global using BankingSystem.Application.Extensions;