// <auto-generated />
using System;
using BankingSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(BankingSystemDbContext))]
    partial class BankingSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankingSystem.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef149a3e-2c0f-45ef-b358-908fa8aa431e"),
                            City = "Sofia",
                            Country = "Bulgaria",
                            CreatedAt = new DateTime(2025, 6, 19, 15, 1, 4, 498, DateTimeKind.Utc).AddTicks(2235),
                            IsDeleted = false,
                            Number = "123",
                            PostalCode = "1000",
                            Street = "Main St."
                        });
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ApplicationRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a03cb524-1815-4b14-8ea3-e6a3dd206c48"),
                            CreatedAt = new DateTime(2025, 6, 19, 15, 1, 4, 497, DateTimeKind.Utc).AddTicks(4270),
                            Description = "Default user role with basic permissions.",
                            IsDeleted = false,
                            Name = "NormalUser"
                        },
                        new
                        {
                            Id = new Guid("6fd4d239-a763-4ee9-a125-2d5348a0665a"),
                            CreatedAt = new DateTime(2025, 6, 19, 15, 1, 4, 497, DateTimeKind.Utc).AddTicks(4278),
                            Description = "Administrator role with full permissions.",
                            IsDeleted = false,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e12bde0e-828c-409b-8087-84450617dcd8"),
                            CreatedAt = new DateTime(2025, 6, 19, 15, 1, 4, 497, DateTimeKind.Utc).AddTicks(812),
                            CreatedBy = "System",
                            Email = "SysAdmin@gmail.com",
                            FirstName = "Sys",
                            IsDeleted = false,
                            LastName = "Admin",
                            PasswordHash = "XMb6cl4NnZEV4mNQCGoLCJ0aU/H//ZK1IAIcyxvZvAOUaVoTyZAB+ZBpQz9fhZQCtSvjdHg5yjxDQB7DyeEScw==",
                            PasswordSalt = "VEyOlH78ICKzMbFs/99lHZ+XmWsVSw1XoQ2O9ymigRcLE8aBf8Ebq4rBEh1kcsYZqJHs2+MSQE83m5X8Q8aEWzbqgizJ1kYB8rKN7gT+GSFQ9u7Mmal7MyCraMYe0s3BVshqO4FO1Y0gQkWVtL+6CWnfAWwZOF+x7iMcQsbXp1U=",
                            PhoneNumber = "1234567890",
                            UserName = "SysAdmin"
                        },
                        new
                        {
                            Id = new Guid("270c2aff-3a9b-4cdd-8eaf-b77181cc7c9b"),
                            CreatedAt = new DateTime(2025, 6, 19, 15, 1, 4, 497, DateTimeKind.Utc).AddTicks(918),
                            CreatedBy = "System",
                            Email = "NormalUser@gmail.com",
                            FirstName = "Normal",
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "4ZTQ/j0CN2KvXIwGoEM2f9rPZ+T09wVc5Ek0JHkIZkP1BeZaYiPNIA2cptImGC+6dX8zBSNRaeIKyOuSgIhaZQ==",
                            PasswordSalt = "Vox9j92SyA5tFQqDWR+NlUfHsxfqdZ6qD+NcGxiVbnEXlBD02TnbbLz/y64dwBWS/xAikghVRVwKlcts5XLnbfbbm7uuB9WjC1eTpV2j7180bOwHe/NFYDpVNH7fwj3Bn6p/wYv2XOEH2mXTIDeEufhHFZOtvJtP/cQrkF/zyzg=",
                            PhoneNumber = "0987654321",
                            UserName = "NormalUser"
                        });
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ApplicationUserRole");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e12bde0e-828c-409b-8087-84450617dcd8"),
                            RoleId = new Guid("6fd4d239-a763-4ee9-a125-2d5348a0665a")
                        },
                        new
                        {
                            UserId = new Guid("270c2aff-3a9b-4cdd-8eaf-b77181cc7c9b"),
                            RoleId = new Guid("a03cb524-1815-4b14-8ea3-e6a3dd206c48")
                        });
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BoardingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MainAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SecondAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MainAddressId")
                        .IsUnique();

                    b.HasIndex("PartnerId");

                    b.HasIndex("SecondAddressId")
                        .IsUnique()
                        .HasFilter("[SecondAddressId] IS NOT NULL");

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c751a11-50a3-4574-b65d-ca3272b13fd5"),
                            BoardingDate = new DateTime(2025, 6, 19, 15, 1, 4, 501, DateTimeKind.Utc).AddTicks(1046),
                            Country = "Bulgaria",
                            CreatedAt = new DateTime(2025, 6, 19, 15, 1, 4, 501, DateTimeKind.Utc).AddTicks(1021),
                            IsDeleted = false,
                            MainAddressId = new Guid("ef149a3e-2c0f-45ef-b358-908fa8aa431e"),
                            Name = "Acme Online Store",
                            PartnerId = new Guid("bf9b7e93-aa9a-4686-b770-b6184245514e"),
                            URL = "https://acmestore.com"
                        });
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf9b7e93-aa9a-4686-b770-b6184245514e"),
                            CreatedAt = new DateTime(2025, 6, 19, 15, 1, 4, 501, DateTimeKind.Utc).AddTicks(3546),
                            IsDeleted = false,
                            Name = "Acme Financial Group"
                        });
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ExternalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceIBAN")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TargetIBAN")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.ApplicationUserRole", b =>
                {
                    b.HasOne("BankingSystem.Domain.Entities.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankingSystem.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.Merchant", b =>
                {
                    b.HasOne("BankingSystem.Domain.Entities.Address", "MainAddress")
                        .WithOne()
                        .HasForeignKey("BankingSystem.Domain.Entities.Merchant", "MainAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingSystem.Domain.Entities.Partner", "Partner")
                        .WithMany("Merchants")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankingSystem.Domain.Entities.Address", "SecondAddress")
                        .WithOne()
                        .HasForeignKey("BankingSystem.Domain.Entities.Merchant", "SecondAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MainAddress");

                    b.Navigation("Partner");

                    b.Navigation("SecondAddress");
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("BankingSystem.Domain.Entities.Merchant", "Merchant")
                        .WithMany("Transactions")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.Merchant", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankingSystem.Domain.Entities.Partner", b =>
                {
                    b.Navigation("Merchants");
                });
#pragma warning restore 612, 618
        }
    }
}
